Rinbuffer option
PAICookers/PAIBox pull request #161
Opened 2024-12-30 08:54 UTC by yang1556

2024-12-31 02:03 UTC, KafCoppelia requested changes

2024-12-31 02:03 UTC, KafCoppelia commented on tests/onboard/test_onboard.py
> +    # @pytest.mark.xfail(
这三行直接删掉就好

2024-12-31 03:01 UTC, yang1556 commented on paibox/components/_modules.py
> +        rin_buffer_option: bool = False,
目前我暴露出来是想测试在设置twe和不设置twe的上板行为，方便测试。后期就隐藏

2024-12-31 03:02 UTC, yang1556 commented on paibox/components/_modules.py
> +            if not HwConfig.N_TIMESLOT_MAX / (2**E) > rin_deep:
同意

2024-12-31 05:55 UTC, KafCoppelia commented on paibox/components/_modules.py
> +            if not HwConfig.N_TIMESLOT_MAX / (2**E) > rin_deep:
修改以后再push上来

2025-01-01 12:32 UTC, KafCoppelia approved these changes

2025-01-01 12:33 UTC, merged